RINGCENTRAL_SERVER: https://platform.ringcentral.com
RINGCENTRAL_CHATBOT_CLIENT_ID: xxx
RINGCENTRAL_CHATBOT_CLIENT_SECRET: xxx
RINGCENTRAL_CHATBOT_ADMIN_USERNAME: admin
RINGCENTRAL_CHATBOT_ADMIN_PASSWORD: xxx
RINGCENTRAL_CHATBOT_DATABASE_USERNAME: tylerliu
RINGCENTRAL_CHATBOT_DATABASE_PASSWORD: xxx
RINGCENTRAL_CHATBOT_DATABASE_CONNECTION_URI:
  Fn::Join:
    - ""
    - - postgresql://tylerliu:xxx@
      - "Fn::GetAtt": [Database, Endpoint.Address]
      - /dbname
RINGCENTRAL_CHATBOT_SERVER:
  Fn::Join:
    - ""
    - - "https://"
      - Ref: ApiGatewayRestApi
      - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
