RINGCENTRAL_SERVER: https://platform.ringcentral.com
RINGCENTRAL_CHATBOT_DATABASE_CONNECTION_URI: postgresql://user@pass@xxxxx.us-east-1.rds.amazonaws.com/prod-db
RINGCENTRAL_CHATBOT_CLIENT_ID:
RINGCENTRAL_CHATBOT_CLIENT_SECRET:
RINGCENTRAL_CHATBOT_SERVER: https://xxxxxxx.execute-api.us-east-1.amazonaws.com/prod
