service:
  name: glip-crontab-chatbot
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 256
  environment: ${file(./.env.yml)}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
package:
  exclude:
    - ./**
    - '!dist/**'
    - '!node_modules/**'
  excludeDevDependencies: true
functions:
  app:
    handler: dist/lambda.app
    timeout: 300 # 5 miutes
  proxy:
    handler: dist/lambda.proxy
    events:
      - http: 'ANY {proxy+}'
  crontab:
    handler: dist/lambda.crontab
    events:
      - schedule: cron(* * * * ? *)
